### ISSUE TITLE
麻烦帮忙看下这个问题

### ISSUE THREAD

**Issue by liangkun16** [un-pany/v3-admin-vite#67]
error.ts:14 ElementPlusError: [ElPagination] 你使用了一些已被废弃的用法，请参考 el-pagination 的官方文档
    at debugWarn (error.ts:13:37)
    at Proxy.<anonymous> (pagination.ts:203:9)
    at renderComponentRoot (runtime-core.esm-bundler.js:914:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5649:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at instance.update (runtime-core.esm-bundler.js:5763:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5777:9)
    at mountComponent (runtime-core.esm-bundler.js:5559:9)
    at processComponent (runtime-core.esm-bundler.js:5517:17)
    at patch (runtime-core.esm-bundler.js:5119:21)
    
  这个是控制台输出的，我也不太懂前端。

**Comment by liangkun16** [comment]
不用看了，是我的我问题，少了一个total字段
